### ISSUE TITLE
npm install of dependencies of dotnext branch

### ISSUE THREAD

**Issue by ghost** [bjnortier/shapesmith.deprecated#102]
Hey ben,

I am curiosu to see how its all going ad want to pull the branch and have a go.

But lathe is the wrong version.
I checked our lathe repo and in the package.json its marked as v0.1.0, but in the shapsmith dotnext branch the package.json is asking for lath v 0.2.0

npm ERR! Error: No compatible version found: lathe@'>=0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0"]
npm ERR!     at installTargetsError (c:\Program Files\nodejs\node_modules\npm\lib\cache.js:709:10)
npm ERR!     at next (c:\Program Files\nodejs\node_modules\npm\lib\cache.js:688:17)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\lib\cache.js:668:5
npm ERR!     at saved (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd c:_data\play\Shapesmith\dotnext
npm ERR! node -v v0.10.10
npm ERR! npm -v 1.2.25

**Comment by ghost** [comment]
oh i just saw the develop branch of lathe has v0.2.0

i will clone that instead.

maybe you could update the dotnext branch to have the right reference ?

g

**Comment by ghost** [comment]
Fixed with "lathe": "git://github.com/bjnortier/lathe.git#develop", in the packae.json

**Comment by ghost** [comment]
all running.

I dont know what stage this project is at.
But i get an obvious error
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8000/node_modules/lathe/node_modules/gl-matrix/dist/gl-matrix.js

**Comment by bjnortier** [comment]
These are being developed in parallel I cannot create a new lathe release every 5 minutes.
The best way is to checkout lathe separately, then do in the shapesmith repo

```
$ npm link ../lathe
```

this will use the local lathe as a dependency. I've just push some changes to lathe (which fixes the missing gl-matrix). After updating it requires an npm install
