### ISSUE TITLE
Undo Redo

### ISSUE THREAD

**Issue by morriswinkler** [bjnortier/shapesmith.deprecated#103]
I could not find any undo redo function, both are fundamental, without editing will get very frustrating, i think adding this feature will enhance usability enormously

**Comment by bjnortier** [comment]
Use the browser back/forward buttons...
—

**Comment by morriswinkler** [comment]
thanks 

Morris Winkler

Open 3D Engineering Winkler & de Vries GbR
Petersburger Strasse 26
10249 Berlin ( Germany )

USt-IdNr.: DE287747941

Bank Account:

GLS Gemeinschaftsbank eG
Christstr. 9, 44789 Bochum
Germany 

Account: 1148086300
Bank no: 43060967

IBAN: DE28430609671148086300
BIC: GENODEM1GLS 

Am 29.06.2013 um 00:45 schrieb Benjamin Nortier:

**Comment by bjnortier** [comment]
Pleasure
—
