### ISSUE TITLE
Build of "node" component brittle wrt bcrypt updates?

### ISSUE THREAD

**Issue by cmundi** [bjnortier/shapesmith.deprecated#46]
Platform is Ubuntu 11.10 x64 but should not matter.

It appears that when the build for "node" pulls its dependencies, it pulls latest of bcrypt but is intolerant of newer-than-expected versions:

Cloning into bcrypt...
ERROR: Dependency dir /home/cmundi/Projects/shapesmith/shapesmith/node/deps/bcrypt failed application validation with reason:
{version_mismatch,{"/home/cmundi/Projects/shapesmith/shapesmith/node/deps/bcrypt/src/bcrypt.app.src",
                   {expected,"0.4.0"},
                   {has,"0.4.1"}}}.
make: **\* [deps] Error 1

**Comment by cmundi** [comment]
This should be easy to work around, assuming the version does not really matter, but I'd like to know.  This is my first time building shapesmith, so I want to save my debugging time for things which are actually peculiar to my environment.  Thanks!

**Comment by bjnortier** [comment]
Thanks for that. The version number for the tag was wrong in their repo, but I see that they fixed it:
https://github.com/smarkets/erlang-bcrypt/commit/97f6b01f28b43712969269f4b6ec5b83c4c28529

I've pushed a change to master and made a 0.7.4 tag with this fix.

**Comment by cmundi** [comment]
Cool.  And thanks.  I'm intrigued by what you've built.
On Apr 16, 2012 1:21 AM, "Benjamin Nortier" <
reply@reply.github.com>
wrote:
