### ISSUE TITLE
requestAnimationFrame is used to update the display

### ISSUE THREAD

**Issue by GriffenJBS** [bjnortier/shapesmith.deprecated#52]
This doesn't affect desktop/wired units, but I'm using this from a wireless device so it keeps the CPU/GPU running hot. Unless I'm missing something the display only needs to be rendered on user events, load, mousemove, etc; that would let the CPU/GPU idle most of the time. Is there some canvas animation happening that I'm missing in the source?

**Comment by bjnortier** [comment]
I think it would be feasible to only animate on these events as you have mentioned, this is also a problem for me when I work on my laptop. Using requestAnimationFrame() is a historical artifact, but it does centralise redraws, and adding redraws in the correct places should be handled with care (but is nonetheless something that I think needs doing)

**Comment by bjnortier** [comment]
This was less difficult that I expected, definitely worth the effort - thanks for the suggestion. Implemented in 0.9.1 (and also deployed on cloud.shapesmith.net). Re-open if you see any rendering issues (i.e. not seeing an update when you should)
