### ISSUE TITLE
picking is a bit too hard

### ISSUE THREAD

**Issue by ghost** [bjnortier/shapesmith.deprecated#54]
its hard to pick the transformation points.
Might be easier if they enlarge as you get close to them ?
Or put in wireframe mode, and leave rest of mode not in wirefreame

**Comment by bjnortier** [comment]
I agree - it would be quite useful to have the interactive UI elements scale with the zoom factor, so that you can still use them reasonably when zoomed out

**Comment by ghost** [comment]
its a bit how sketchup does it.

they also have groups and the other bits grey out as you drill into the groups

On 24 May 2012 16:10, Benjamin Nortier
reply@reply.github.com
wrote:

**Comment by bjnortier** [comment]
Interactive elements now maintain their pixel size, regardless of the camera distance
