### ISSUE TITLE
physics

### ISSUE THREAD

**Issue by ghost** [bjnortier/shapesmith.deprecated#55]
Physijs is physics with threejs
Its on git hub and is a nice integration with three

I know its a bit early but integrating physics into a solid modelling engine designed for 3d printing is pretty smart.
You will be able to simulate something you are designing working in many ways.

I really think that shapesmith is the best webgl cad thing i have seen. Its architecture is perfect for doing amazing things going forward. Sorry but just  happy this thing exists.

**Comment by bjnortier** [comment]
I'm happy that you're happy :) 

I agree on the physics stuff - I did an experiment on Shapesmith + Ammo.js, which was very encouraging. Video here:
https://vimeo.com/41003021

The model designer is useful, but there are many modellers out there. It's the integration and the API that's really where the future lies for Shapesmith

**Comment by ghost** [comment]
wow i just wrote you an email and basically said the same thing but extended it

On 24 May 2012 19:49, Benjamin Nortier
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
watch this.

As a building architect this knocks my socks off.

http://block.arch.ethz.ch/tools/rhinovault/tutorials/1
