### ISSUE TITLE
Run the tests command on Ubuntu:   $ ./rebar compile eunit ct skip_deps=true

### ISSUE THREAD

**Issue by MikaAndy83** [bjnortier/shapesmith.deprecated#88]
I have arrived at this point of installation:
## Build the Erlang application

From within shapesmith/nodes:

```
.../shapesmith/nodes$ make    OK
```

NB. Because of the cookies used in the session authentication tests, add the following line to the /etc/hosts file:

```
127.0.0.1       localhost.shapesmith.net (OK)
```

Run the tests:
   $ ./rebar compile eunit ct skip_deps=true - (5 TEST FAILED)

![errorSS](https://f.cloud.github.com/assets/3089182/24218/5bc4932e-4a95-11e2-84cf-ebce2a1044ca.jpg)

![Immagine](https://f.cloud.github.com/assets/3089182/24229/298392d8-4a96-11e2-8a45-f06474834ae8.jpg)

When i can do?thanks

**Comment by bjnortier** [comment]
Hmmm. It's strange that some tests pass and others fails because of connection errors. Can you start it up successfully? Does this work? 

```
$ ./start-dev.sh
```

**Comment by MikaAndy83** [comment]
This work but if i go into my browser at http://localhost:8000 return general "server not found "!

**Comment by bjnortier** [comment]
What is the output when you start the server? There should be no errors. For example, mine shows:

```
$ ./start-dev.sh 
Erlang R15B01 (erts-5.9.1) [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.9.1  (abort with ^G)
(master@127.0.0.1)1> 09:15:46.014 [info] Application lager started on node 'master@127.0.0.1'
09:15:46.025 [info] Application folsom started on node 'master@127.0.0.1'
09:15:46.039 [info] Application worker_master started on node 'master@127.0.0.1' 
09:15:46.047 [info] worker node 'master@127.0.0.1' joined master node 'master@127.0.0.1'
09:15:46.049 [info] starting worker process for:    "/Users/bjnortier/development/shapesmith/nodes/apps/worker/priv/build/worker"
09:15:46.052 [info] worker <0.71.0> available. total available: 1
09:15:46.054 [info] starting worker process for:    "/Users/bjnortier/development/shapesmith/nodes/apps/worker/priv/build/worker"
09:15:46.055 [info] worker <0.72.0> available. total available: 2
09:15:46.056 [info] Application worker started on node 'master@127.0.0.1'
09:15:46.124 [info] Application inets started on node 'master@127.0.0.1'
09:15:46.150 [info] Application crypto started on node 'master@127.0.0.1'
09:15:46.159 [info] Application bcrypt started on node 'master@127.0.0.1'
09:15:46.165 [info] Application mochiweb started on node 'master@127.0.0.1'
** Found 0 name clashes in code paths 
09:15:46.238 [info] Application webmachine started on node 'master@127.0.0.1'
opening log file: "priv/log/access.log.2012_12_21_09"
09:15:46.257 [info] Application api started on node 'master@127.0.0.1'
```

**Comment by MikaAndy83** [comment]
This is my result!..in the first row he gets angry on etc/host file:

---

administrator@administrator-VirtualBox:~/Projects/shapesmith/nodes$ ./start-dev.sh
/etc/host.conf: line 4: bad command `127.0.0.1       localhost.shapesmith.net'
Erlang R15B01 (erts-5.9.1) [source] [async-threads:0] [kernel-poll:false]

Eshell V5.9.1  (abort with ^G)
(master@127.0.0.1)1> 10:26:38.767 [info] Application lager started on node 'master@127.0.0.1'
10:26:38.785 [info] Application folsom started on node 'master@127.0.0.1'
10:26:38.803 [info] Application worker_master started on node 'master@127.0.0.1' 
10:26:38.814 [info] worker node 'master@127.0.0.1' joined master node 'master@127.0.0.1'
10:26:38.819 [info] starting worker process for: "/home/administrator/Projects/shapesmith/nodes/apps/worker/priv/build/worker"
10:26:38.821 [info] worker <0.72.0> available. total available: 1
10:26:38.822 [info] starting worker process for: "/home/administrator/Projects/shapesmith/nodes/apps/worker/priv/build/worker"
10:26:38.834 [info] worker <0.73.0> available. total available: 2
10:26:38.835 [info] Application worker started on node 'master@127.0.0.1'
10:26:38.979 [info] Application inets started on node 'master@127.0.0.1'
10:26:39.045 [info] Application crypto started on node 'master@127.0.0.1'
10:26:39.064 [info] Application bcrypt started on node 'master@127.0.0.1'
10:26:39.077 [info] Application mochiweb started on node 'master@127.0.0.1'
*\* Found 0 name clashes in code paths 
10:26:39.209 [info] Application webmachine started on node 'master@127.0.0.1'
opening log file: "priv/log/access.log.2012_12_21_09"
10:26:39.247 [info] Application api started on node 'master@127.0.0.1'

**Comment by hyperkang** [comment]
@MikaAndy83 

I had better luck than you and  I was able to get it installed successfully. :)

Here is my best guess for the issue you encountered:
1. The instalation guidance says file /etc/hosts should be modified, not /etc/host.conf.
2. I am not sure if it matters, but I use one TAB instead of SPACEs between "127.0.0.1" and "localhost.shapesmith.net" in my  /etc/hosts.

PS, I am using Ubuntu 12.x installed with VMware on Win7.

**Comment by bjnortier** [comment]
Thanks @hyperkang, yes it should be in /etc/hosts

**Comment by MikaAndy83** [comment]
Thanks so much!My stupid mistake!i have confuse file config!now i get one test error!but the shapesmith html page is on!

**Comment by bjnortier** [comment]
Great! You can close the issue if you're happy that it's resolved

**Comment by MikaAndy83** [comment]
I'am very unlucky!..When i click on create Design the firefox crash everytime!..i open new Issue? :(

**Comment by bjnortier** [comment]
Yes you can open a new issue. At this point Firefox not properly supported
though - Chrome is the primary browser supported.

On Fri, Dec 21, 2012 at 10:17 AM, MikaAndy83 notifications@github.comwrote:

> I'am very unlucky!..When i click on create Design the firefox crash
> everytime!..i open new Issue? :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bjnortier/shapesmith/issues/88#issuecomment-11608441.

## 

Benjamin Nortier
bjnortier@gmail.com
http://www.twitter.com/bjnortier
http://www.1011ltd.com
+44 (0)778 946 1959
